services:
  db:
    image: mysql:8.0
    container_name: event-management-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_DATABASE:-event_management}
      MYSQL_USER: ${DB_USER:-events_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-events_password}
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/internal/infrastructure/mysql/init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - ./backend/internal/infrastructure/mysql/migrations/001_initial_schema.sql:/docker-entrypoint-initdb.d/01-initial-schema.sql
      - ./backend/internal/infrastructure/mysql/migrations/002_seed_data.sql:/docker-entrypoint-initdb.d/02-seed-data.sql
      - ./backend/internal/infrastructure/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: event-management-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/vendor
    environment:
      - ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-event_management}
      - DB_USER=${DB_USER:-events_user}
      - DB_PASSWORD=${DB_PASSWORD:-events_password}
      - GIN_MODE=debug
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: event-management-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data: 