openapi: 3.0.3
info:
  title: イベント管理システム API
  description: イベント管理システムのRESTful API
  version: 1.0.0
  contact:
    name: 開発チーム
    email: dev@example.com

servers:
  - url: http://localhost:8080
    description: 開発環境

paths:
  /events:
    get:
      summary: イベント一覧を取得
      operationId: getEvents
      parameters:
        - name: page
          in: query
          description: ページ番号
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: 1ページあたりの件数
          required: false
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventList"
        "400":
          description: バリデーションエラー
        "500":
          description: サーバーエラー

    post:
      summary: 新しいイベントを作成
      operationId: createEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateEventRequest"
      responses:
        "201":
          description: イベント作成成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        "400":
          description: バリデーションエラー
        "500":
          description: サーバーエラー

  /events/{eventId}:
    get:
      summary: イベント詳細を取得
      operationId: getEvent
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        "404":
          description: イベントが見つかりません
        "500":
          description: サーバーエラー

    put:
      summary: イベントを更新
      operationId: updateEvent
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateEventRequest"
      responses:
        "200":
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        "400":
          description: バリデーションエラー
        "404":
          description: イベントが見つかりません
        "500":
          description: サーバーエラー

    delete:
      summary: イベントを削除
      operationId: deleteEvent
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: 削除成功
        "404":
          description: イベントが見つかりません
        "500":
          description: サーバーエラー

components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: イベントID
        name:
          type: string
          description: イベント名
        description:
          type: string
          description: イベントの説明
        startDate:
          type: string
          format: date-time
          description: 開始日時
        endDate:
          type: string
          format: date-time
          description: 終了日時
        status:
          type: string
          enum: [draft, published, cancelled, completed]
          description: イベントのステータス
        createdAt:
          type: string
          format: date-time
          description: 作成日時
        updatedAt:
          type: string
          format: date-time
          description: 更新日時
      required:
        - id
        - name
        - startDate
        - endDate
        - status

    EventList:
      type: object
      properties:
        events:
          type: array
          items:
            $ref: "#/components/schemas/Event"
        pagination:
          $ref: "#/components/schemas/Pagination"

    CreateEventRequest:
      type: object
      properties:
        name:
          type: string
          description: イベント名
        description:
          type: string
          description: イベントの説明
        startDate:
          type: string
          format: date-time
          description: 開始日時
        endDate:
          type: string
          format: date-time
          description: 終了日時
      required:
        - name
        - startDate
        - endDate

    UpdateEventRequest:
      type: object
      properties:
        name:
          type: string
          description: イベント名
        description:
          type: string
          description: イベントの説明
        startDate:
          type: string
          format: date-time
          description: 開始日時
        endDate:
          type: string
          format: date-time
          description: 終了日時
        status:
          type: string
          enum: [draft, published, cancelled, completed]
          description: イベントのステータス

    Pagination:
      type: object
      properties:
        page:
          type: integer
          description: 現在のページ番号
        limit:
          type: integer
          description: 1ページあたりの件数
        total:
          type: integer
          description: 総件数
        totalPages:
          type: integer
          description: 総ページ数

    Error:
      type: object
      properties:
        message:
          type: string
          description: エラーメッセージ
        code:
          type: string
          description: エラーコード
